services:
  testtask.api:
    image: testtask.api
    build:
      context: .
      dockerfile: src/TestTask.Api/Dockerfile
    networks:
      - app-networtk

  database:
    image: 'postgres:latest'
    ports:
      - 1432:5432
    env_file:
      - .env
    volumes:
      - db-lib-data:/var/lib/postgresql/data/

  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    networks:
      - app-networtk

networks:
  app-networtk:
    driver: bridge


volumes:
  db-lib-data:
  pgadmin-data:
