services:
  testtask.api:
    image: testtask.api
    build:
      context: .
      dockerfile: src/TestTask.Api/Dockerfile

  testtask.ui:
    image: testtask.ui
    build:
      context: .
      dockerfile: src/TestTask.UI/Dockerfile
