services:
  testtask.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CalculationDb=Host=database;Port=5432;Database=test-task;Username=postgres;Password=postgres
    expose:
      - "8080"
      - "8081"
    ports:
        - "5000:8080"
    networks:
      - app-networtk

  testtask.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CalculationDb=Host=database;Port=5432;Database=test-task;Username=postgres;Password=postgres
      - SystemHttpClientsSettings__TestTast=http://testtask.api:8080
    expose:
      - "8080"
      - "8081"
    ports:
      - "5001:8080"
    networks:
      - app-networtk

  database:
    image: 'postgres:latest'
    ports:
      - 1432:5432
    env_file:
      - .env
    volumes:
      - db-lib-data:/var/lib/postgresql/data/
    networks:
      - app-networtk

  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
      - "5671:5671"
    networks:
      - app-networtk

networks:
  app-networtk:
    driver: bridge

volumes:
  db-lib-data:
  pgadmin-data:
